### ISSUE TITLE
Infografia Marcos

### ISSUE THREAD

**Issue by MarcosJonathan17** [SistemasTecTlaxiaco/infografia-MarcosJonathan17#1]
![WhatsApp Image 2022-02-23 at 12 39 55 PM](https://user-images.githubusercontent.com/79876660/155385784-e28208b6-eedb-4090-b67a-7da82b449ee5.jpeg)

**Comment by Nancy2050** [comment]
Puntaje 14/20

**Comment by josealfredo79** [comment]
Falta complementar esta infografia

**Comment by josealfredo79** [comment]
Revisado
