### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by MarcosJonathan17** [SistemasTecTlaxiaco/infografia-MarcosJonathan17#5]
[ingeniería de requisitos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-MarcosJonathan17/files/6185988/ingenieria.de.requisitos.pdf)

**Comment by ElvisS10** [comment]
Buena trabajo! La infografía esta bien solo que hay que tratar de estructurar mejor la información pero de ahí todo bien! 
**Calificación:18%***

**Comment by ThorSampy** [comment]
El diseño esta bien, el único detalle es que contiene mucho texto.

**Comment by Anna-Aparicio** [comment]
Toda la información es importante, solo que en este tipo de trabajo es preferible menos texto ya que con las imágenes se debe complementar

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
